In [2]:
import numpy as np

# Basics


In [3]:
# One Dimension 
a = np.array([1,4,5] , dtype = 'int32')

In [3]:
a 

array([1, 4, 5])

In [6]:
# Two Dimension 

b = np.array([[2.6,5.0,6.0],[4.0,2.0,7.0]])

In [8]:
b

array([[2., 5., 6.],
       [4., 2., 7.]])

In [11]:
# Get Dimension 
a.ndim 


1

In [12]:
b.ndim

2

In [14]:
#Get Shape
a.shape

(3,)

In [15]:
b.shape

(2, 3)

In [18]:
# Get type 
a.dtype

dtype('int16')

In [19]:
b.dtype

dtype('float64')

In [23]:
#Get size 
a.itemsize 

4

In [21]:
b.itemsize 

8

In [24]:
# Get total size 
a.nbytes

12

In [25]:
b.nbytes

48

# Accessing / chanfinf specific elements ,row , columns ,etc

In [32]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
x

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [33]:
#Get a specific items/elements  (r,c)

x[1,5]


np.int64(13)

In [34]:
# Get a specific row 
x[1,:]


array([ 8,  9, 10, 11, 12, 13, 14])

In [36]:
x[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
#Get specific coloumn 
x[:,1]

array([2, 9])

In [41]:
x[:,5]

array([ 6, 13])

In [44]:
# Getting a little more fancy [startIndex : endIndex :step_size ]

x[1,1:6:2]

array([ 9, 11, 13])

In [45]:
x[0,1:-2:2]

array([2, 4])

In [46]:
# Element Change 

x[1,3] = 20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 20 12 13 14]]


In [48]:
# all column value change 

x[:,4]=100
print(x)

[[  1   2   3   4 100   6   7]
 [  8   9  10  20 100  13  14]]


# 3D example 

In [54]:
b = np.array([[[1,2,8],[3,4,9]],[[3,9,0],[9,8,4]]])
print(b)

[[[1 2 8]
  [3 4 9]]

 [[3 9 0]
  [9 8 4]]]


In [58]:
#Get specific element (work outside in) 

b[1,1,2]

np.int64(4)

In [60]:
b[:,1,:]

array([[3, 4, 9],
       [9, 8, 4]])

In [61]:
#Replace 
b[:,1,:] = ([[4,5,6],[4,4,4]])


In [62]:
b

array([[[1, 2, 8],
        [4, 5, 6]],

       [[3, 9, 0],
        [4, 4, 4]]])

Initializing Different Type of arrary 

In [65]:
#All 0s matrix 

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
# All 1s matrix 
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [71]:
# Any other numbers 
np.full((2,2),99) 

array([[99, 99],
       [99, 99]])

In [72]:
#Randam decimal value 

np.random.rand(4,2)

array([[0.94667975, 0.12306104],
       [0.60719445, 0.79217979],
       [0.47780869, 0.83812263],
       [0.98145152, 0.09466664]])

In [73]:
#The identity matrirx 

np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
#repeat arrary 
arr = np.array([[2,3,4]])
np.repeat(arr,3)


array([2, 2, 2, 3, 3, 3, 4, 4, 4])

# Mathematics


In [78]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [79]:
a+2 

array([3, 4, 5, 6])

In [80]:
a-2

array([-1,  0,  1,  2])

In [81]:
a*2

array([2, 4, 6, 8])

In [82]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [83]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear algebra 


In [84]:
#Find the determinat 
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

# Statistics


In [86]:
stats = np.array([[1,2,3],[4,2,5]])
stats


array([[1, 2, 3],
       [4, 2, 5]])

In [87]:
np.min(stats)

np.int64(1)

In [88]:
np.max(stats)

np.int64(5)

In [89]:
np.sum(stats)

np.int64(17)